[velox]
build_args = [
    '-trimpath',
    '-ldflags',
    '-s -X github.com/roadrunner-server/roadrunner/v2/internal/meta.version=${VERSION} -X github.com/roadrunner-server/roadrunner/v2/internal/meta.buildTime=${TIME}',
]

[roadrunner]
ref = "v2.12.3"

[github]
[github.token]
token = "${RT_TOKEN}"

# ref -> master, commit or tag
[github.plugins]
# LOGS
appLogger = { ref = "v3.2.0", owner = "roadrunner-server", repository = "app-logger" }
logger = { ref = "v3.2.0", owner = "roadrunner-server", repository = "logger" }

# CENTRIFUGE BROADCASTING PLATFORM
centrifuge = { ref = "v3.2.0", owner = "roadrunner-server", repository = "centrifuge" }

# WORKFLOWS ENGINE
temporal = { ref = "v3.0.0", owner = "temporalio", repository = "roadrunner-temporal" }

# METRICS
metrics = { ref = "v3.3.0", owner = "roadrunner-server", repository = "metrics" }

# HTTP + MIDDLEWARE
http = { ref = "v3.2.0", owner = "roadrunner-server", repository = "http" }
gzip = { ref = "v3.2.0", owner = "roadrunner-server", repository = "gzip" }
prometheus = { ref = "v3.2.0", owner = "roadrunner-server", repository = "prometheus" }
headers = { ref = "v3.2.0", owner = "roadrunner-server", repository = "headers" }
static = { ref = "v3.2.0", owner = "roadrunner-server", repository = "static" }
otel = { ref = "v3.2.0", owner = "roadrunner-server", repository = "otel" }

# RELOAD (for the DEV)
reload = { ref = "v3.2.0", owner = "roadrunner-server", repository = "reload" }

# SERVER
server = { ref = "v3.2.0", owner = "roadrunner-server", repository = "server" }

# SERVICE aka lightweit systemd
service = { ref = "v3.2.0", owner = "roadrunner-server", repository = "service" }

# JOBS
jobs = { ref = "v3.2.0", owner = "roadrunner-server", repository = "jobs" }
amqp = { ref = "v3.3.0", owner = "roadrunner-server", repository = "amqp" }
sqs = { ref = "v3.3.0", owner = "roadrunner-server", repository = "sqs" }
beanstalk = { ref = "v3.2.0", owner = "roadrunner-server", repository = "beanstalk" }
nats = { ref = "v3.2.0", owner = "roadrunner-server", repository = "nats" }
kafka = { ref = "v3.0.4", owner = "roadrunner-server", repository = "kafka" }

# KV
kv = { ref = "v3.2.0", owner = "roadrunner-server", repository = "kv" }
boltdb = { ref = "v3.2.0", owner = "roadrunner-server", repository = "boltdb" }
memory = { ref = "v3.3.0", owner = "roadrunner-server", repository = "memory" }
redis = { ref = "v3.2.0", owner = "roadrunner-server", repository = "redis" }
memcached = { ref = "v3.2.0", owner = "roadrunner-server", repository = "memcached" }

# FILESERVER (static files)
fileserver = { ref = "v3.2.0", owner = "roadrunner-server", repository = "fileserver" }

# gRPC plugin
grpc = { ref = "v3.3.0", owner = "roadrunner-server", repository = "grpc" }

# HEALTHCHECKS + READINESS CHECKS
status = { ref = "v3.2.0", owner = "roadrunner-server", repository = "status" }

# TCP for the RAW TCP PAYLOADS
tcp = { ref = "v3.2.0", owner = "roadrunner-server", repository = "tcp" }

[gitlab]
[gitlab.token]
# api, read-api, read-repo
token = "${GL_TOKEN}"

[gitlab.endpoint]
endpoint = "https://gitlab.com"

[gitlab.plugins]
# ref -> master, commit or tag
test_plugin_1 = { ref = "main", owner = "rustatian", repository = "36405203" }
test_plugin_2 = { ref = "main", owner = "rustatian", repository = "36405235" }

[log]
level = "debug"
mode = "development"
